version: "3.5"

services:
  plugins.glpi-project.org:
    container_name: "${CONTAINER_NAME:-plugins.glpi-project.org}"
    restart: "${CONTAINER_RESTART_POLICY:-unless-stopped}"
    build:
      context: "."
      args:
        HOST_GROUP_ID: "${HOST_GROUP_ID:-1000}"
        HOST_USER_ID: "${HOST_USER_ID:-1000}"
    ports:
      - "${HTTP_PORT_APACHE:-8000}:80"
      - "${HTTP_PORT_NODEJS:-9000}:9000"
      - "${HTTP_PORT_LIVERELOAD:-35729}:35729"
    volumes:
      - type: "bind"
        source: "../.."
        target: "/var/www/plugins.glpi-project.org"
    extra_hosts:
      - "host.docker.internal:host-gateway"
